### ISSUE TITLE
where is the rmarkdown file for golden_rules.html?

### ISSUE THREAD

**Issue by liamxg** [JorgensenD/coursepage#1]
I like your golden_rules.html file very much, where to find the origin file, thanks.

**Comment by JorgensenD** [comment]
Hi, this coursepage was for an R epidemics consortium training course. The golden rules files live in this repo: https://github.com/reconhub/guides and other training materials are available through the website: https://www.reconlearn.org/

**Comment by liamxg** [comment]
thanks, you are very nice.
